# Stop Nginx.
- name: Stop Nginx
  command: supervisorctl {{item}} nginx
  loop:
    - stop
    - remove
  tags:
    - stop

# Stop App.
- name: Stop App
  command: supervisorctl {{item}} app
  loop:
    - stop
    - remove
  tags:
    - stop
