# Fetch App Git repository.
- name: Fetch App Git repository
  git:
    repo: "{{app.repo_url}}"
    version: master
    dest: "{{app.deploy_dir}}"
    update: yes
    force: yes
  tags:
    - update

# Install App Python packages.
- name: Install App Python packages
  command: pip install -r requirements.txt
  args:
    chdir: "{{app.deploy_dir}}"
  tags:
    - update
