# Install system packages.
- name: Install system packages
  yum:
    name:
      - tcl
    state: present
  tags:
    - setup

# Create Redis directories.
- name: Create Redis directories
  file:
    path: "{{item}}"
    state: directory
    owner: root
    group: root
    recurse: true
    mode: 0700
  loop:
    - "{{redis.config_dir}}"
    - "{{redis.system_dir}}"
    - "{{redis.log_dir}}"
    - "{{redis.data_dir}}"
  tags:
    - setup

# Download and extract Redis.
- name: Download and extract Redis
  unarchive:
    src: http://download.redis.io/releases/redis-{{redis.version}}.tar.gz
    dest: /tmp
    owner: root
    group: root
    remote_src: yes
    creates: /tmp/redis-{{redis.version}}
  tags:
    - setup

# Compile and install Redis.
- name: Compile and install Redis
  command: "{{item}}"
  args:
    chdir: /tmp/redis-{{redis.version}}
  loop:
    - make distclean
    - make
    - make install
  tags:
    - setup

# Cleanup source.
- name: Cleanup source
  file:
    path: /tmp/redis-{{redis.version}}
    state: absent
    owner: root
    group: root
    mode: 0700
  tags:
    - setup
