version: '3.8'
services:
  app:
    image: sloopstash/ansible:v1
    command: "/usr/bin/supervisord -c /etc/supervisord.conf"
    hostname: crm-app
    ports:
      - "2221-2225:22"
      - "8081-8085:80"
    volumes:
      - ../../supervisor/conf/main.conf:/etc/supervisord.conf
      - ../../supervisor/conf/sshd.ini:/etc/supervisord.d/sshd.ini
    depends_on:
      - redis
    networks:
      - ansible-net
  redis:
    image: sloopstash/ansible:v1
    command: "/usr/bin/supervisord -c /etc/supervisord.conf"
    hostname: crm-redis
    ports:
      - "2231:22"
    volumes:
      - ../../supervisor/conf/main.conf:/etc/supervisord.conf
      - ../../supervisor/conf/sshd.ini:/etc/supervisord.d/sshd.ini
    networks:
      - ansible-net
networks:
  ansible-net:
    external:
      name: ansible-net
